### ISSUE TITLE
Remove (useless) ic_launcher from resources due collision

### ISSUE THREAD

**Issue by trajakovic** [jaydeepw/android-utils#10]
Please remove (useless) resources from res folder, and please check this out http://stackoverflow.com/a/29977893/1137445. 

Long story short - if you need resources, please prefix them with some project abbreviation ie. aul, and make aapt happy again.

**Comment by jaydeepw** [comment]
Fixed and published a new version

https://github.com/jaydeepw/android-utils/tree/master#v302

**Comment by trajakovic** [comment]
cool, thx
